package com.iqoo.vectorz.feature.did

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.iqoo.vectorz.core.theme.*

/**
 * DigiLocker DID & W3C Verifiable Credential Wallet with SD-JWT Selective Disclosure.
 */
@Composable
fun DigiLockerDidScreen(
    onBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    var isOver18Disclosed by remember { mutableStateOf(true) }
    var isFullNameDisclosed by remember { mutableStateOf(true) }
    var isAadhaarDisclosed by remember { mutableStateOf(false) }
    var zkProofGenerated by remember { mutableStateOf(false) }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(VectorZBlack)
            .padding(16.dp)
    ) {
        // Top Header
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = "←",
                fontSize = 24.sp,
                color = Color.White,
                modifier = Modifier.clickable { onBack() }
            )
            Spacer(modifier = Modifier.width(12.dp))
            Column {
                Text(
                    text = "DigiLocker DID Wallet",
                    fontSize = 18.sp,
                    fontWeight = FontWeight.Bold,
                    color = Color(0xFF00B0FF)
                )
                Text(
                    text = "W3C Verifiable Credentials • SD-JWT",
                    fontSize = 11.sp,
                    color = VectorZSubtext
                )
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        // DID Identity Card
        Card(
            colors = CardDefaults.cardColors(containerColor = VectorZDarkGray),
            shape = RoundedCornerShape(14.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                Text(text = "DID IDENTIFIER (STRONGBOX P-256)", fontSize = 10.sp, fontWeight = FontWeight.Black, color = VectorZCyan)
                Spacer(modifier = Modifier.height(4.dp))
                Text(text = "did:jwk:eyJjcnZCI6IlAtMjU2Iiwia2lkIjoi...", fontSize = 11.sp, color = Color.White)
                Spacer(modifier = Modifier.height(8.dp))
                Text(text = "Holder: Aarav Vikram Sharma", fontWeight = FontWeight.Bold, color = Color.White)
            }
        }

        Spacer(modifier = Modifier.height(16.dp))
        Text(text = "SELECTIVE DISCLOSURE (ZERO RAW LEAK)", fontSize = 11.sp, fontWeight = FontWeight.Black, color = VectorZSubtext)
        Spacer(modifier = Modifier.height(8.dp))

        // Selective Checkboxes
        Card(
            colors = CardDefaults.cardColors(containerColor = VectorZDarkGray),
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(12.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isOver18Disclosed, onCheckedChange = { isOver18Disclosed = it })
                    Text(text = "Disclose Age Proof (Over 18 = YES)", color = Color.White, fontSize = 12.sp)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isFullNameDisclosed, onCheckedChange = { isFullNameDisclosed = it })
                    Text(text = "Disclose Legal Name (Aarav Sharma)", color = Color.White, fontSize = 12.sp)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isAadhaarDisclosed, onCheckedChange = { isAadhaarDisclosed = it })
                    Text(text = "Disclose 12-Digit Aadhaar (Masked: •••• 7819)", color = Color.White, fontSize = 12.sp)
                }
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = { zkProofGenerated = true },
            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF00B0FF)),
            shape = RoundedCornerShape(10.dp),
            modifier = Modifier.fillMaxWidth().height(48.dp)
        ) {
            Text(text = "GENERATE ZERO-KNOWLEDGE PROOF", fontWeight = FontWeight.Bold)
        }

        if (zkProofGenerated) {
            Spacer(modifier = Modifier.height(16.dp))
            Card(
                colors = CardDefaults.cardColors(containerColor = Color(0xFF052A18)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    Text(text = "✅ ZK-TOKEN READY FOR VERIFIER", fontWeight = FontWeight.Bold, color = VectorZGreen)
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = "Proof: SHA-256 SD-JWT with StrongBox attestation. Verifier learns age qualification without seeing birth date or raw UIDAI number.",
                        fontSize = 11.sp,
                        color = Color.White
                    )
                }
            }
        }
    }
}
