package com.iqoo.vectorz.ai.truth

import com.iqoo.vectorz.ai.inference.LocalInferenceEngine
import com.iqoo.vectorz.core.model.AtomicClaim
import com.iqoo.vectorz.core.model.TruthAuditReport
import com.iqoo.vectorz.core.model.TruthStatus

class TruthAuditEngine(private val inferenceEngine: LocalInferenceEngine) {

    suspend fun auditContent(rawTextOrClaim: String): TruthAuditReport {
        val lower = rawTextOrClaim.lowercase()
        val claimsList = mutableListOf<AtomicClaim>()

        // 1. Extract atomic claims
        val extractedRaw = inferenceEngine.extractAtomicClaims(rawTextOrClaim)

        var hasDisputed = false
        var hasSupported = false

        for (claim in extractedRaw) {
            val cLower = claim.lowercase()
            when {
                cLower.contains("free electricity") || cLower.contains("government giving 50000") || cLower.contains("rbi lottery") -> {
                    hasDisputed = true
                    claimsList.add(
                        AtomicClaim(
                            claimText = claim,
                            status = TruthStatus.DISPUTED,
                            evidenceSnippets = listOf(
                                "PIB Fact Check: Debunked official government scheme claim.",
                                "RBI Advisory: RBI never issues lottery winnings or prize notifications."
                            )
                        )
                    )
                }
                cLower.contains("offline e-kyc") || cLower.contains("uidai") || cLower.contains("digilocker") -> {
                    hasSupported = true
                    claimsList.add(
                        AtomicClaim(
                            claimText = claim,
                            status = TruthStatus.SUPPORTED,
                            evidenceSnippets = listOf(
                                "UIDAI Official Documentation: Offline Paperless e-KYC is a valid identity mechanism."
                            )
                        )
                    )
                }
                else -> {
                    claimsList.add(
                        AtomicClaim(
                            claimText = claim,
                            status = TruthStatus.UNVERIFIED,
                            evidenceSnippets = listOf(
                                "No authoritative government or official press release found in local database cache."
                            )
                        )
                    )
                }
            }
        }

        // Synthetic media / generative cues
        val isSyntheticCue = lower.contains("generated by ai") || lower.contains("deepfake") ||
                lower.contains("synthetic voice") || lower.contains("midjourney") || lower.contains("chatgpt")

        val syntheticSignals = if (isSyntheticCue) "ELEVATED" else "LOW"

        val overallStatus = when {
            hasDisputed -> TruthStatus.DISPUTED
            hasSupported && !hasDisputed -> TruthStatus.SUPPORTED
            else -> TruthStatus.UNVERIFIED
        }

        val explanation = when (overallStatus) {
            TruthStatus.DISPUTED -> "Central claims contradict known official regulatory advisories. Evidence indicates social media forward / fabricated notice."
            TruthStatus.SUPPORTED -> "Claims align with documented regulatory facts."
            TruthStatus.UNVERIFIED -> "Unable to conclusively verify claims from local evidence cache. Exercise independent caution."
        }

        return TruthAuditReport(
            overallStatus = overallStatus,
            confidence = if (overallStatus == TruthStatus.DISPUTED) 0.94f else 0.76f,
            atomicClaims = claimsList,
            syntheticMediaSignals = syntheticSignals,
            explanation = explanation,
            sourcesConsulted = listOf("PIB Fact Check Registry", "RBI Public Notices", "UIDAI Reference Portal")
        )
    }
}
